name: âœ… test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: utooland/setup-utoo@v1
      - run: ut
      - run: ut prestart
      - run: ut lint
      - run: ut tsc
      - run: ut compile
      - run: ut coverage
      - run: ut test:dekko
      - uses: codecov/codecov-action@v5
        with:
          directories: packages/x,packages/x-markdown,packages/x-sdk
          token: ${{ secrets.CODECOV_TOKEN }}
